### ISSUE TITLE
Could not pre-render route; Must use import to load ES Module

### ISSUE THREAD

**Issue by joshuavachon25** [freddy38510/quasar-app-extension-ssg#105]
Hi,
I got one error when trying to generate my site:
```bash
Could not pre-render route

Must use import to load ES Module: C:\...\node_modules\three\examples\jsm\controls\OrbitControls.js require() of ES modules is not supported. 
require() of C:\...\node_modules\three\examples\jsm\controls\OrbitControls.js from C:\...\node_modules\.cache\quasar-app-extension-ssg is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
Instead rename OrbitControls.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from C:\...\node_modules\three\examples\jsm\package.json.
```
It's a file from ThreeJS working well in SPA, but I don't know what is going on when trying SSG. I don't use require()

Thanks in advance for you help!

**Comment by freddy38510** [comment]
Hi,

You might run this library only at client side. SSG pre-render your pages at server side.

Quoted from the [three.js installation documentation](https://threejs.org/docs/#manual/en/introduction/Installation) :

> Using three.js in Node.js can be difficult, for two reasons:
> 
> First, because three.js is built for the web, it depends on browser and DOM APIs that don't always exist in Node.js. Some of these issues can be resolved by using shims like headless-gl, or by replacing components like TextureLoader with custom alternatives. Other DOM APIs may be deeply intertwined with the code that uses them, and will be harder to work around. We welcome simple and maintainable pull requests to improve Node.js support, but recommend opening an issue to discuss your improvements first.
> 
> Second, Node.js support for ES modules is ... complicated. As of Node.js v12, the core library can be imported as a CommonJS module, with require('three'). However, most example components in examples/jsm cannot. Future versions of Node.js may resolve this, but in the meantime you may need to use workarounds like esm to enable your Node.js application to recognize ES modules.

Try to use a [boot file](https://quasar.dev/quasar-cli/developing-ssr/writing-universal-code#boot-files) and/or use `process.env.CLIENT` || `process.env.SERVER` in your Vue components.

**Comment by joshuavachon25** [comment]
Thanks for your answer!
I'm new to Quasar, so, how would write this boot file? (The file is created, but do I create a new OrbitControls in that file or can I do it in my page?)

**Comment by freddy38510** [comment]
This is beyond the scope of the extension. It depends on three.js that I didn't know about until now.

An simple way to do this that I can think of is to create a Vue component that handles your use of three.js then wrap it in a [Quasar `<no-ssr>` component](https://quasar.dev/vue-components/no-ssr). This way the component will only run on the client side.
