### ISSUE TITLE
Is it neccesary to use preFetch?

### ISSUE THREAD

**Issue by franco-onevillas** [freddy38510/quasar-app-extension-ssg#108]
Hi Freddy,

Thank you for this extension, i am trying to implement it but I was wondering if its necessary to use `preFetch` to be able to generate the pages with all the dynamic data. If I don't and make an api call in `setup()` the source code is empty.

Regards,
Franco.

**Comment by freddy38510** [comment]
Hi Franco,

It is not necessary to use `preFetch` but this is a reliable way to handle async data with SSG.

In which lifecycle hook do you make the api call ?
`beforeMount` and `mounted` hooks are only executed at client-side so you could try to make your api call in `created` hook instead.

Another way I can think of is to fetch and save your data in json files before building your application. Then you can just import the json files where you need them.
Using this way you can also take advantage of the code-splitting feature to avoid putting the json files content inside the client page bundle by loading it asynchronously on the client-side (so it could be cached separately).

**Comment by franco-onevillas** [comment]
Hi Freddy, thank you for the answer.

I tried on `beforeCreate` and `created` – `setup()` on composition API – because, as you said, these are the only hooks available on SSR but when I inspect the source code its empty.

Sounds good, I will give it a try and see how it works with the vuex store :)

Thank you again, regards

**Comment by freddy38510** [comment]
You're welcome @franco-onevillas.

If you don't want to use Vuex you can take a look at this repository https://github.com/dongnaebi/vue3-SSR-starter and try to get inspiration from the `syncState` object.

**Comment by franco-onevillas** [comment]
@freddy38510 Wow, that's awesome, I will also give it a try.

Thanks again and I hope that this extension gets to the Quasar docs :)

**Comment by franco-onevillas** [comment]
Hi again @freddy38510,

I ask you here to not open a new issue. Everything is working as expected except from that when I load (from scratch) any page, for example:
- /a
- /b
It redirects to:
- /a/
- /b/ 

I realised because of the url and the lighthouse report. Is there any configuration for this? I was looking at the docs and I didn't see anything,

Thank you

**Comment by franco-onevillas** [comment]
Yes, sure:

```
"quasar": "^2.1.0",`
"@quasar/cli": "^1.2.1",
"@quasar/extras": "^1.11.0",
```

```
import { RouteRecordRaw } from 'vue-router';

const routes: RouteRecordRaw[] = [
  // Hero layout
  {
    path: '/',
    alias: '/home',
    component: () => import('layouts/HeroLayout.vue'),
    children: [
      { path: '', component: () => import('pages/Index.vue') },
      { path: 'about-us', component: () => import('src/pages/Services.vue') },
      { path: 'services', component: () => import('src/pages/Services.vue') },
    ],
  },

  // Main layout
  {
    path: '/',
    component: () => import('layouts/MainLayout.vue'),
    children: [
      {
        path: 'wishlist',
        component: () => import('src/pages/Wishlist.vue'),
      },
      {
        path: 'terms-and-conditions',
        component: () => import('src/pages/Legal.vue'),
      },
      {
        path: 'privacy-policy',
        component: () => import('src/pages/Legal.vue'),
      },
      {
        path: 'cookies',
        component: () => import('src/pages/Legal.vue'),
      },
    ],
  },

  // Search layout
  {
    path: '/huis-ibiza',
    component: () => import('layouts/SearchLayout.vue'),
    children: [
      {
        path: '',
        component: () => import('pages/Search.vue'),
      },
    ],
  },
  {
    path: '/huis-ibiza',
    component: () => import('layouts/MainLayout.vue'),
    children: [{ path: ':slug', component: () => import('pages/House.vue') }],
  },

  // Always leave this as last one,
  // but you can also remove it
  {
    path: '/:catchAll(.*)*',
    component: () => import('pages/Error404.vue'),
  },
];

export default routes;
```

**Comment by freddy38510** [comment]
Your Vue Router configuration seems fine.

I'm pretty sure your issue is with the server you are using. I just tried with the server from the "quasar ssg serve" command and there is no redirect with a trailing slash added to the url.

Can you provide more details about that ?

**Comment by freddy38510** [comment]
The redirection is coming from the [express.js server provided](https://github.com/freddy38510/quasar-app-extension-ssg/blob/master/src/bin/server.jsl) by the command `quasar ssg serve` which I assume you are using.

This is the expected behavior to have consistent Urls especially for SEO.

If you really want to have no redirection with trailing slash, you can use your own server with the appropriate configuration.
For express.js the option `redirect` of `express.static` middleware should be set to `false`. Then you need to send the corresponding index.html file in response to each request.

```javascript
app.get('*', (req, res) => {
  res.sendFile(path.join(rootPath, req.url, './index.html'));
});
```

**Comment by franco-onevillas** [comment]
That's nice, I didn't know that so thanks again.

And if I want to keep that behavior, should I add the `"/"` on Vue Router configuration? Because I don't want the lighthouse report messing the performance.

**Comment by freddy38510** [comment]
You can keep your Vue Router configuration as is and adapt your server to redirect url with trailing slash to url without trailing slash.
Or you can do the opposite by adding trailing slash in your Vue Router configuration.

The important thing is to be consistent to optimize SEO by avoiding duplicate content available at two different urls, one with trailing slash, and the other without.

About Vue Router configuration the new version v4 for Vue3 had made this change ["Named children routes with an empty path no longer appends a slash"](https://next.router.vuejs.org/guide/migration/index.html#named-children-routes-with-an-empty-path-no-longer-appends-a-slash):

> Reason: This is to make trailing slash behavior consistent: by default all routes allow a trailing slash. It can be disabled by using the strict option and manually appending (or not) a slash to the routes.

**Comment by franco-onevillas** [comment]
Great, i was looking at the same thing :)

btw, do you need more hands on the extension development?

Let me know!

**Comment by freddy38510** [comment]
Sure,

All PR are welcome.

One feature that I think is missing a lot from this extension is a dev mode as mentioned in [this issue](https://github.com/freddy38510/quasar-app-extension-ssg/issues/2).

**Comment by francoromanol** [comment]
Hey @freddy38510 , sorry I am on vacation and I just see this message.

Great, I will check it! Another amazing feature would be [Incremental statoc regeneration](https://vercel.com/docs/concepts/next.js/incremental-static-regeneration)

Let me know what do you think :), I will check the other issue.

Regards,
Franco.
