### ISSUE TITLE
Error when using Quasar Meta plugin

### ISSUE THREAD

**Issue by dfk7677** [freddy38510/quasar-app-extension-ssg#110]
Hi there and thanks for your great work!

When using the Meta plugin of Quasar and your extension to statically generate the routes, I get an error in the browser, only for the routes that I have excluded from statically rendering.

The error reads: 
`Uncaught (in promise) TypeError: Cannot read properties of null (reading 'remove')`
and is caused by the following JS code:
`document.getElementById("qmeta-init").remove())`

Note here that the error appears even when there is no use of the Meta plugin in the specific page (or at all), just by activating it in the quasar.conf.js and the page doesn't even show up.

Steps to reproduce:
1. Create a new project.
2. Add the Meta plugin in quasar.conf.js.
3. Create a new route.
4. Exclude it from SSG.
5. Build, serve and open the url of the above route in the browser.
6. Optionally change the spa fallback to something other than 404.html to not get the 404 error.

**Comment by freddy38510** [comment]
Hi @dfk7677 ,

Thanks for opening this issue as it might affect other parts of the running app when falling back to SPA on first load, which is your case when navigating directly to excluded routes.

Could you try the latest version I just released and tell me how it's going for you?

**Comment by dfk7677** [comment]
Hi and thanks for the quick answer!
It works! But now that I see you resolve issues so quickly I have some more for you :P

Have a nice day!
