### ISSUE TITLE
Not working with other app extension

### ISSUE THREAD

**Issue by vandelpavel** [freddy38510/quasar-app-extension-ssg#16]
I created a project where i used an app extension called `@dreamonkey/animate` that you can find here  `https://github.com/dreamonkey/quasar-app-extension-animate.git`.
Later when applying SSG AE this error will show up:
```
  SyntaxError: Cannot use import statement outside a module
...
 Extension(ssg) · ⚠️  SyntaxError: Cannot use import statement outside a module
```

I think the problem is relative to webpack that can't transpile the dependency of the other app extension.

### repro
https://github.com/vandelpavel/app-esxtension-test.git

You can try to launch `quasar dev` and scrolling the page will activate the animations.
But when you try to launch `quasar ssg build` it will throw that error.

**Comment by hawkeye64** [comment]
@vandelpavel What happens if you do this:
```
quasar build -m ssr
```

**Comment by vandelpavel** [comment]
With `quasar build -m ssr` it works.
I also tried `quasar build -m ssr --static` wich is the one in the read-me and it's no long working.

**Comment by freddy38510** [comment]
@vandelpavel, @hawkeye64

I tried to run `quasar build -m ssr` and the build complete fine.

But if you start the standalone webserver with `node index.js` inside the previously generated folder `dist/ssr` you've got the same error than with `quasar ssg build`.

So i added the dependency for transpiling with babel, then there is no more error and the animations works great.
```javascript
transpileDependencies: [/@dreamonkey[\\/]quasar-app-extension-animate/]
```

**Comment by vandelpavel** [comment]
Ok cool now it works thanks!
But before closing the issue i would like to ask another quesion. That was just a reoro case so when i added the line on the original project the console throws 'Extension(ssg) · ⚠️  ReferenceError: window is not defined'
I think thaqt the problem may be the same that on server/side window can not be used.. But i cant find where is used.
I'm inesperienced so any help or a hint on what i should do to find a solution would be very helpfull!

**Comment by freddy38510** [comment]
@vandelpavel could you give us more details ?

What is a "reoro case" ?

>when i added the line on the original project

Which line are you talking about ?

You are right about `window` it's a browser-only global that you cannot access from server-side.

The stack trace of the error could help a lot.

**Comment by vandelpavel** [comment]
Sorry i ment "repro case", the github repository to reproduce the error.
The line that you supplied:
```transpileDependencies: [/@dreamonkey[\\/]quasar-app-extension-animate/]```
The problem is that it doesn't really give an actual stack trace.... Here is the log:
```
...
 App · Extension(ssg): Running afterBuild hook...
 Extension(ssg) · Generating route /...
[  ReferenceError: window is not defined

  - 1.92e8cf77.js:1 L
    js/1.92e8cf77.js:1:11858

  - 1.92e8cf77.js:1 r
    js/1.92e8cf77.js:1:11620

  - 1.92e8cf77.js:1 Module.eea6
    js/1.92e8cf77.js:1:58898

  - server-bundle.js:1 n
    server-bundle.js:1:194

  - task_queues.js:97 processTicksAndRejections
    internal/process/task_queues.js:97:5

]
 Extension(ssg) · ⚠️  ReferenceError: window is not defined
```

**Comment by freddy38510** [comment]
I can't reproduce it with the repository you gave.

Try to run `quasar build -m ssr --static --debug`

**Comment by vandelpavel** [comment]
I was trying to modify the previeus repro but unfortunally when creating other pages it keeps saying "404 on /<path>" when changing the path.
It works just if the path doesn't have a layout like so:
```{
    path: '/',
    component: () => import('layouts/MainLayout.vue'),
    children: [{ path: '', component: () => import('pages/Index.vue') }]
  },
  {
    path: '/p',
    component: () => import('layouts/MainLayout.vue'),
    children: [{ path: '', component: () => import('pages/Page-two.vue') }]
  },```

But assume that we have something like: 
```
...
path: '/',
    component: () => import('layouts/frame.vue'),
    children: [
      { path: '', component: () => import('pages/home.vue') },
...
```

**Comment by vandelpavel** [comment]
I just realized that on the repo works but not on the project. I don't know why.... I just deleted node modules, quasar folder

**Comment by freddy38510** [comment]
I think that you missed an uppercase.

`layouts/frame.vue` doesn't exist.
Does `layouts/Frame.vue` exists ?

If you can't find where the global `window` is used in your project files, maybe it is coming from some dependencies you are importing. Try to import them only at client side.

With Quasar you can use `process.env.SERVER` or `process.env.CLIENT` in your Vue components.

If you are using boot files it's even easier. Quote from Quasar docs :

> When building a SSR app, you may want some boot files to run only on the server or only on the client, in which case you can do so like below:

> ```javascript
> boot: [
>  {
>    server: false, // run on client-side only!
>    path: '<name>' // references /src/boot/<name>.js
>  },
>  {
>    client: false, // run on server-side only!
>    path: '<name>' // references /src/boot/<name>.js
>  }
> ]
> ```

You could also try to debug errors by putting the parameter `debug` to your Quasar command.
`quasar build -m ssr --static --debug`

**Comment by vandelpavel** [comment]
No uppercase error, they are reported on log fortunally.
Actually now the problem as i said "I was trying to modify the previeus repro but unfortunally when creating other pages it keeps saying "404 on /" when changing the path." (probably i wasn't clear sorry) the problem is the routing.

**Comment by vandelpavel** [comment]
I'll close this issue and open another one.

**Comment by vandelpavel** [comment]
By the way i found why it was saying that window was not defined.
I discovered that window was used inside a mixin (As you said) 
``If you can't find where the global window is used in your project files, maybe it is coming from some dependencies you are importing. Try to import them only at client side.``
