### ISSUE TITLE
error  '_q' is defined but never used  no-unused-vars

### ISSUE THREAD

**Issue by vandelpavel** [freddy38510/quasar-app-extension-ssg#18]
Every time i invoke the AE it keeps rewriting the `src/boot/bodyClasses.js` (obviously unless i skip that step).
Doing so it will keep adding the `_q` variable that is never used throwing an error on build time.
I suggest something like:
```js
export default ({ app }) => {
  queues.takeover.push((/*_q*/) => {
    const cls = getBodyClasses(client, app);

    if (client.is.ie === true && client.is.versionNumber === 11) {
      cls.forEach(c => document.body.classList.add(c));
    } else {
      document.body.classList.add.apply(document.body.classList, cls);
    }
  });
};
```

**Comment by freddy38510** [comment]
I just updated the master branch. You can see a better docs now that i suggest you to read carefully. Old code is in this branch https://github.com/freddy38510/quasar-app-extension-ssg/tree/v0.0.1

So, i recommend you to update the ssg app extension dependency in your project.

You should not having issue with `bodyClasses` now. Let me know if all is okay for you.

**Comment by vandelpavel** [comment]
I can't actually intall it. I think to have removed all the old dependencies but i get:
```
Hp@LAPTOP-MSS9NBB6 MINGW64 ~/Documents/Sources/athenia (feature/add-ssg-feat)
$ yarn add --dev https://github.com/freddy38510/quasar-app-extension-ssg
yarn add v1.21.1
[1/5] Validating package.json...
[2/5] Resolving packages...
error Command failed.
Exit code: 128
Command: git
Arguments: pull
Directory: C:\Users\Hp\AppData\Local\Yarn\Cache\v6\.tmp\5548252b3d125c0bfc42c214bf309478
Output:
fatal: refusing to merge unrelated histories
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
```

**Comment by vandelpavel** [comment]
I also tried with `--allow-unrelated-histories` option and also tried in the test project and in a brand new project.
Keeps sending the same error.

**Comment by freddy38510** [comment]
You have to clean the cache dependencies to remove old history of this repo.

`yarn cache clean`

**Comment by vandelpavel** [comment]
Oh thank you i didn't know that. You are teaching me lots of things doing that. Now i'll rewiew everithing :)

**Comment by vandelpavel** [comment]
Maybe later i'll send you a PR where i see some errors but i've noticed `Serve
This extension provides a command to create a server for testing your static site localy:`
think you ment `Locally* `

**Comment by freddy38510** [comment]
You are welcome to contribute to this project, do not hesitate.

This extension need more testing to be considered as stable. So i will be glad to see all possibles feedbacks, including errors in the documentation.

Concerning the actual issue, let me know if you have errors related to TypeScript with the last version.

**Comment by vandelpavel** [comment]
I think my problems originated due to a series of instructions used to create a SSG with a different mechanism and when i removed them i simply missed something somewhere that hidered this mechanism.
By the way... no more problem with `bodyClasses`. I encountered some errors but i need to check the causes.
In case of need i'll open another issue. I think this one can be closed.
Awesome job! 👍

**Comment by freddy38510** [comment]
Thank for your feedback @vandelpavel, i close it now.
