### ISSUE TITLE
Schema validation error when enabling `inlineCssFromSFC`

### ISSUE THREAD

**Issue by IlCallo** [freddy38510/quasar-app-extension-ssg#188]
Hey there!
I enabled `inlineCssFromSFC` just for fun and got this error.

![image](https://user-images.githubusercontent.com/10036108/157697836-d28739b1-f557-47da-92b8-b0a5794e2828.png)

It seems that into https://github.com/freddy38510/quasar-app-extension-ssg/commit/854d84f6f2f8253a60d42bb9f33429370af998b2 one of the `plugins` assignments is placed one level too high, can't understand which one unluckily

**Comment by freddy38510** [comment]
Hey!

Thanks you for reporting this issue. This did not show up in my tests.

Ps: I'm actually trying to add lazy/partial hydration using the Vue 3 API. It's almost done, I just need to test it in many scenarios.
