### ISSUE TITLE
Failing build when providing a `build > distDir`

### ISSUE THREAD

**Issue by IlCallo** [freddy38510/quasar-app-extension-ssg#20]
Hey there! Really glad you managed to make so much progress on this.
I tried to make the SSG work with a custom `distDir` but it fails due to this part of the extension:

https://github.com/freddy38510/quasar-app-extension-ssg/blob/c68d9675b4a86545aaddae9258d75e62bf102df1/src/index.js#L29-L32

Here you initialize the `conf.ssg.__distDir` option, but only if `conf.build.distDir` isn't provided.
Later on, you use it as input for `join` function, but if `conf.build.distDir` is set you'll get an undefined `conf.ssg.__distDir`.

I guess you meant to use `conf.build.distDir` as default value and provide a fallback when it's not defined.
You can accomplish this by changing the code to

```js
conf.ssg.__distDir = conf.build.distDir || join(api.appDir, 'dist', 'ssg')
```

I tried it out on-the-fly and it fixes the problem with my project generation

**Comment by freddy38510** [comment]
Thanks @IlCallo to notice that issue !

I totally messed up the distDir when i reviewed my code. Before that, custom distDir was working.

I will push a commit soon, thanks again :)

**Comment by vandelpavel** [comment]
I'm having the same problem.
AE version: 3.1.4

```
Extension(ssg) • Copying assets...
  Error: Could not copy assets
  
  ENOENT: no such file or directory, lstat '/media/avandelli/DataShared_NTFS/projects/quasar-v2-test-ssg/dist/spa/public/www'
  ```
  
  ```js
  await fs.copy(
      join(quasarConf.build.distDir, 'www'),
      quasarConf.ssg.__distDir,
    );
    ```
    
    Found that  `join(quasarConf.build.distDir, 'www')` doesn't exist in that moment.
    I can see that inside the dist folder while building the folder structure it's present but then gets deleted.

**Comment by vandelpavel** [comment]
@freddy38510 I need to do more investigation on why but could it be that the `clean` function is called too early here?

https://github.com/freddy38510/quasar-app-extension-ssg/blob/master/src/generate/index.js#:~:text=%7D%3B-,banner(api%2C%20ctx%2C%20%27generate%27)%3B,%7D,-try%20%7B

**Comment by freddy38510** [comment]
I just tried setting `build.distDir` to `'test'` and it worked fine.

Could you provide the `build.distDir` and `ssg.buildDir` values that you set in your `quasar.conf.js` file ?

I guess you are mixing the two paths, they shouldn't be the same.

- `build.distDir` is the path to the distributables folder which is "cleaned" just before the extension generates the pages.
- `ssg.buildDir` is the path to the webpack build output folder from which the extension can prerender pages.

**Comment by vandelpavel** [comment]
Yes i was using the same path. (`dist/spa/public`)

So...
If i want to use the build path i can avoid to specify the `buildDir` inside the ssg configuration.
If i want to use a different path, i can use the `buildDir` to change it. In that case i must ensure that the 2 paths do not conflict eachother. Right @freddy38510?

**Comment by freddy38510** [comment]
> So... If i want to use the build path i can avoid to specify the `buildDir` inside the ssg configuration. If i want to use a different path, i can use the `buildDir` to change it. In that case i must ensure that the 2 paths do not conflict eachother. Right? @freddy38510

That's right, the `ssg.buildDir` option [is documented in the README](https://github.com/freddy38510/quasar-app-extension-ssg#builddir). By [default](https://github.com/freddy38510/quasar-app-extension-ssg#cache) this *separate* folder is [cached](https://github.com/freddy38510/quasar-app-extension-ssg#about-cache-feature) to avoid rebuilding the whole app with webpack when nothing has changed.

The `build.distDir` option is `dist/ssg` by default. The extension tries to stick to the [Quasar documentation](https://quasar.dev/quasar-cli/quasar-conf-js#property-build):
"Folder where Quasar CLI should generate the distributables. Relative path to project root directory. Default is ‘dist/{ctx.modeName}’."

> The build works ok and i can serve it but then keep i getting this error on each page i visit:
GET http://localhost:4000/ 404 (Not Found)

If you change the default value of `build.distDir` you have to serve your app from your custom folder:
```bash
quasar ssg serve your-custom-folder
```

**Comment by vandelpavel** [comment]
One last question. So if i want to create different builds in different folders i need to only change `build.distDir` depending by the build context. At the other end `ssg.buildDir` is used only for build performance and not for defining the final folder of the ssg build. Is that right?

**Comment by freddy38510** [comment]
You can build your app several times with different modes and set the dist folder based on your needs.
Setting `build.distDir` to `‘your-custom-folder/{ctx.modeName}’` is one way to do that.

But you should know that `ctx.modeName` is set to `ssr` when your run the command `quasar ssg generate`.
To differentiate ssr mode from ssg, you can use [`process.env.STATIC`](https://github.com/freddy38510/quasar-app-extension-ssg#processenvstatic) like this:
```javascript
build.distDir = process.env.STATIC ?  'your-custom-folder/ssg' : `your-custom-folder/{ctx.modeName}`;
```

About `ssg.buildDir`, this directory can be considered as an intermediate folder before the final distributable folder. It contains all the assets compiled by webpack plus the needed files to pre-render your pages.
