### ISSUE TITLE
Wrong quasar conf file path on latest Quasar

### ISSUE THREAD

**Issue by NunoSav** [freddy38510/quasar-app-extension-ssg#200]
This plugin targets a specific path for the quasar conf file: https://github.com/freddy38510/quasar-app-extension-ssg/blob/9fba6c918cf28a56c67cac6fce00904d88569240/src/bin/ssg-generate.js#L46

And after updating Quasar to latest and using the webpack flavour the path that would work is:
`@quasar/app-webpack/lib/quasar-conf-file`.

I guess then that the plugin needs to consider multiple options here, right now should be either `app-webpack` or `app-vite`.

**Comment by freddy38510** [comment]
Hello,

I will be pushing a commit to support the latest version of Quasar during the day.

Supporting Vite will take longer, the eco-system is totally different from Webpack.

Thanks for reminding me of this Quasar breaking update :+1:
