### ISSUE TITLE
Prompt options: add scripts

### ISSUE THREAD

**Issue by IlCallo** [freddy38510/quasar-app-extension-ssg#21]
Many AE use Prompt API to ask the dev for some initialization options and take care of scaffolding related code.

I think it could be a good idea to add a "add scripts into your package.json" which automatically adds build and serve commands like so:

```json
{
  "scripts": {
    "build:ssg": "quasar ssg generate",
    "serve:ssg": "quasar ssg serve dist/ssg/public"
  }
}
```

**Comment by freddy38510** [comment]
This is a good idea !

I will implement it shortly. Thanks !
