### ISSUE TITLE
Silent fail on router.js > build in v2.3

### ISSUE THREAD

**Issue by eyedean** [freddy38510/quasar-app-extension-ssg#214]
Greetings,

I have been using `quasar.app.extenions-ssg` for almost a year now and it's great.  Recently I ran into some weird errors on `BeastCss` and upgraded from `2.1.4` to `2.3.0`.

Now when I run it with `--forceBuild` it builds but ends right after finishing the `build` and before starting `generate`.

I started debugging (by putting `console.log` in the source code of `./node_modules/quasar-app-extension-ssg`) and I found that it's failing silently (no error whatsoever) when it cannot get `routerBuildPromise` resolved ever.  I found that it's related to the new `router.js` that is supposed to kick and spit the routes I guess.  (This commit: https://github.com/freddy38510/quasar-app-extension-ssg/commit/5b33845747f5578eabac74a051701489b8856b9a#diff-09b963845cb446391f74c8ba93ecd69d85db6f97f6d03fa997297be1264a7349)

Here is a screenshot of the logs and my code.  (I am sorry that the project is so big and private that I cannot share a repo/demo.)

<img width="944" alt="image" src="https://user-images.githubusercontent.com/5694695/163060814-0d2f51c7-c008-4e68-a1d0-56b2e18c095f.png">

If I simply skip `ensureBuild` function (put a `return;` at the top of it) and instead run a build manually, everything works.  

I am going to dive deeper but meanwhile wanted to ask if you have any idea/clue/suggestion? I will update this issue with any findings/solution that I get to.

Thanks again for this awesome work @freddy38510!

**Comment by eyedean** [comment]
Finding 1: if I put a `await routerBuildPromise;` in `build/index.js` right after where it's created (i.e. [L82](https://github.com/freddy38510/quasar-app-extension-ssg/blob/2.x/src/build/index.js#L82)), it takes like 60 seconds there (one full build time for me) but then everything works.

However, when this await is at the bottom of the function, the code just dies after like 3 seconds there (see the screenshot above).  I suspect something is not patient enough to wait there and I need to find that person!

**Comment by freddy38510** [comment]
Hello @eyedean !

Thanks for investigating and creating such a detailed issue, it helps a lot.

I rewrited a lot of code (that I will backport to v2), including this specific part which compile your app vue-router `src/router/index.js` file. The goal is effectively to get the app routes from a trusted source.

For debugging purpose could you try to replace [this portion of code](https://github.com/freddy38510/quasar-app-extension-ssg/blob/2.x/src/build/router.js#L11&L13) in `quasar-app-extension-ssg/src/build/router.js` file:
```javascript
return new Promise((resolve) => {
  this.webpack(this.webpackConf, async () => resolve());
});
```
by: 
```javascript
return new Promise(resolve => {
  this.webpack(this.webpackConf, async (err, stats) => {
    if (err) {
      console.error(err.stack || err)

      if (err.details) {
        console.error(err.details)
      }

      process.exit(1)
    }

    if (stats.hasErrors() !== true) {
      resolve()
    }

    const info = stats.toJson()

    info.errors.forEach((error) => {
      console.error(error)
    });

    process.exit(1)
  })
})
```

**Comment by eyedean** [comment]
@freddy38510 Thanks for your prompt response!

Unfortunately that didn't help and yielded no output.  The same behavior is still happening -- it exits 3 seconds after finishing `build` and before doing `generate` (basically the build for router is silently dying.)

I was able to put some breakpoints both in your script and webpack (via [this answer of mine](https://stackoverflow.com/a/71864932)) to monitor the behavior closely. I wasn't able to get any exception or log at all (it just dies and exits with no log/output whatsoever), but I have a theory.

## My Theory
In file `build/index.js` ([this file](https://github.com/freddy38510/quasar-app-extension-ssg/blob/2.x/src/build/index.js)) there are two webpack builds being called out:
1. The main build ([L#91](https://github.com/freddy38510/quasar-app-extension-ssg/blob/2.x/src/build/index.js#L91): `await compiler.run();`), and
2. The router's build, which is initiated on [L#82](https://github.com/freddy38510/quasar-app-extension-ssg/blob/2.x/src/build/index.js#L82): `const routerBuildPromise = routerBuilder.build();` and `await`ed in the end at [L#165](https://github.com/freddy38510/quasar-app-extension-ssg/blob/2.x/src/build/index.js#L165).

I believe you made it this way to have the two builds run in parallel (with different configs).

However, I suspect webpack (or some plugins) is freaking out and is unable to handle two instances of it running concurrently, specially with different options/configs.  e.g. it's throwing (and catching) a `ConcurrentCompilationError` (similar to their [/lib/Compiler.js#L425-L427](https://github.com/webpack/webpack/blob/main/lib/Compiler.js#L425-L427).)

### Why is not happening on your machine?
Maybe because the compilation is so fast in your test cases that this concurrency/race-condition doesn't actually occur.  In my case, I have over 1000 components/modules that get compiled and it takes ~2 minutes for each build.

---

## How to fix it?
I have two solutions that both work for me. (I made the change locally and tested them.)

### Solution 1: Build router first, and then the actual compile
i.e. move the `await routerBuildPromise;` of router from L165 to L89, right before the start of the `compiler.run()`.

### Solution 2: Kick router build after the actual compile
i.e. move `routerBuilder.build()` in L82 to L93, after `compiler.run()`.

## Do we need it?
The problem with both solutions above is:
1. It takes twice as long. For me, it's going from ~2 minutes to ~4 minutes.
2. There is absolutely no feedback in the terminal when the router build is going on.

### Solution 3: Have an option to disable router-build and allow the good old "pass an array of routes" options to work.
That would definitely work for me! I am suggesting it in case you couldn't repro and you think the two builds running in parallel should work and probably there is something wrong with my code.

Let me know how do you think.  For now I am going to [patch-package](https://github.com/ds300/patch-package#making-patches) it locally for myself with solution 2 to unblock myself. ;)

Thanks again for taking ownership and providing support to this fabulous package! <3

**Comment by freddy38510** [comment]
You sum it up perfectly here. I really appreciate that you take the time to do that.

Actually the issue (on the 2.x branch) about running two instances of webpack concurrently will be solved in the next commits. 

_(If you are curious, please see [this commit](https://github.com/freddy38510/quasar-app-extension-ssg/commit/101078f585316c37c69f31f8c9cb70c29dc7f3ba), and more particularly this file https://github.com/freddy38510/quasar-app-extension-ssg/blob/master/src/build/webpack/ssg/generator.js#L64 and this one https://github.com/freddy38510/quasar-app-extension-ssg/blob/master/src/build/templates/entry/ssg-get-app-routes-entry.js)_

You brought up the right point by asking the question "do we need it?".
I want to give as much flexibility as possible to the end user, so I will provide an option to disable this feature.  

The process should still take a reasonable amount of time to run. In your case, with a lot of vue components to compile, I hope that [externalizing vue components](https://github.com/freddy38510/quasar-app-extension-ssg/blob/master/src/build/webpack/ssg/generator.js#L84) instead of [replacing it](https://github.com/freddy38510/quasar-app-extension-ssg/blob/2.x/src/webpack/conf.router.js#L35&L38) will significantly reduce this amount of time.

**Comment by eyedean** [comment]
That was very insightful @freddy38510!  I truly appreciate the dedication and care you are putting here.  I am eagerly looking forward to the next release on 2.x! 😍

Thanks.

**Comment by freddy38510** [comment]
I just released a new version for Quasar v2.

I will be backporting all fixes and features to the v2.x branch and avoiding a breaking change by not removing the `process.env.STATIC` environment variable.

As you can see I added an option to not include static routes from the application router. But hopefully you won't get any more warnings using this feature, since the router [is no longer compiled for this specific case](https://github.com/freddy38510/quasar-app-extension-ssg/commit/f3e201fe992d560bbbb5d4da5021d75da2023db6).

**Comment by freddy38510** [comment]
I just published the new [v2.4.0](https://www.npmjs.com/package/quasar-app-extension-ssg/v/2.4.0), please let me know if you have any issues.

**Comment by eyedean** [comment]
Thank you @freddy38510.  I will update the package in the next release and will let you know about the result!

**Comment by eyedean** [comment]
Update: I updated the package to `2.4.0` and now it's working like a charm!  I like the 3 progress-bars for Client/Server/Generator. So nice. :)

Thank you so much @freddy38510!

**Comment by freddy38510** [comment]
It's great!

By the way, [this commit](https://github.com/freddy38510/quasar-app-extension-ssg/commit/6e1da522306b7f6696f7fce92e94af6fc90e11fa) introduced an issue with [`publicPath`](https://v1.quasar.dev/quasar-cli/quasar-conf-js#property-build) setting which is no longer properly defined. I will come with a fix later.

Also, in the master branch, I'm currently implementing a new command (which speaks for itself) `quasar ssg dev`.
