### ISSUE TITLE
Sharing routes paths between router/routes.js and ssg > routes option

### ISSUE THREAD

**Issue by IlCallo** [freddy38510/quasar-app-extension-ssg#22]
I'll drop here a suggestion for an use case, for whom could need it.
I explored a bit how to keep in sync routes path for SSG configuration and router option object.
This is a bit tricky because `quasar.conf.js` is handled as CommonJS, while `router/routes.js` is ES5 syntax and the two cannot be mixed, at least until Quasar CLI files will be transpiled too or Node will finally understand ES modules.

The best I could think of was to store the paths as a string dictionary into `quasar.conf.js`, provide it as an env variable and then retrive and use it into `router/routes.js`.

```js
// quasar.conf.js
const routesPaths = {
  root: '',
  home: 'home',
  archive: 'archive',
  bookDetail: 'book-detail'
};

const routes = Object.values(routesPaths).map(route => {
  return `/${route}`;
});

module.exports = configure(function(ctx) {
  return {
    ssg: { routes },
    build: {
      env: {
        ROUTES_PATHS: routesPaths
      },
    },
    // ... other options
  };
}
```

```js
// router/routes.js
/** @type {Object.<string, string>}  */
const routesPaths = process.env.ROUTES_PATHS;

const routes = [
  {
    path: '/',
    component: () => import('layouts/layout.vue'),
    children: [
      {
        path: routesPaths.root,
        component: () => import('pages/home.vue')
      },
      {
        path: routesPaths.home,
        component: () => import('pages/home.vue')
      },
      {
        path: routesPaths.archive,
        component: () => import('pages/archive.vue'),
      },
      {
        path: routesPaths.bookDetail,
        component: () => import('pages/book-detail.vue'),
      }
    ],
  },
];

// Always leave this as last one
routes.push({
  path: '*',
  component: () => import('pages/error-404.vue'),
});

export default routes;
```

Unluckily I could not find a way to do the opposite yet (automatically build SSG routes from VueRouter configuration), which would be much more useful.
Nuxt does this by crawling the website, which may be an overkill right now.

**Comment by IlCallo** [comment]
I can also see an interesting integration with [auto-routing feature](https://github.com/quasarframework/rfcs/issues/6), when it will be available

**Comment by freddy38510** [comment]
I would like to implement this feature. It could be awesome for projects that have a lot of pages to generate.

What about dynamics routes ?

Crawling the website like Nuxt does, solves this issue. But i agree with you, this is an overkill.

**Comment by IlCallo** [comment]
> What about dynamics routes ?

Good question, I have no idea at all :rofl: 
I'm actually not that skilled into routing, until now I only built projects with few pages so I don't have much experience in that area, but you can try to ask on the Discord server or Quasar Forum if anyone already hit this problem and how they solved it

**Comment by freddy38510** [comment]
I should mention this commit https://github.com/freddy38510/quasar-app-extension-ssg/commit/d0d94e12079cf1753ca61b2d666edbc2852563a7 and this https://github.com/freddy38510/quasar-app-extension-ssg/issues/86#issuecomment-952895602 for reference. This is related to how the extension parse the routes defined in the Vue-Router configuration for Vue 3.
