### ISSUE TITLE
Typescript error due to quasar last version

### ISSUE THREAD

**Issue by benamar** [freddy38510/quasar-app-extension-ssg#223]
Hello
I can't generate!
tsconfig.json does not exist in @quasar module
perhaps I am missing something.

Here is the log:

@Benamars-iMac app-webpack % quasar ssg generate
 App • Looking for Quasar App Extension "ssg" command "generate"
 App • Running "ssg" Quasar App Extension...
 App • Running "ssg" > "generate" command

 ================== BUILD ================== 

 Build mode................ ssg
 Pkg ssg................... v4.1.1
 Pkg quasar................ v2.6.1
 Pkg @quasar/app-webpack... v3.4.3
 Pkg webpack............... v5
 Debugging................. no

 Configured browser support (>= 87.51% of global marketshare):
 · Chrome for Android >= 99
 · Firefox for Android >= 96
 · Android >= 99
 · Chrome >= 90
 · Edge >= 96
 · Firefox >= 89
 · iOS >= 12.2-12.5
 · Opera >= 79
 · Safari >= 13.1

 App • Chaining "Client-side" Webpack config
 App • Chaining "Server-side" Webpack config
 App • Cleaned build artifact: "/Users/benamarbelarbi/git/portedesign/node_modules/.cache/quasar-app-extension-ssg"
/Users/benamarbelarbi/git/portedesign/node_modules/fork-ts-checker-webpack-plugin/lib/typescript-reporter/TypeScriptSupport.js:40
        throw new Error([
              ^

[  Error: Cannot find the "/Users/benamarbelarbi/git/portedesign/node_modules/@quasar/app-webpack/tsconfig.json" file.
  Please check webpack and ForkTsCheckerWebpackPlugin configuration.

**Comment by benamar** [comment]
Sorry I found out
I didn't see my editor was running in the wrong path.
The generation worked fine.

**Comment by freddy38510** [comment]
No problem @benamar, feel free to open an issue if needed.

I'm glad the new version didn't introduce this bug after all.

I just tried running the `quasar build -m ssr` command inside a subfolder of a fresh new project, and the same error was thrown.
