### ISSUE TITLE
http-proxy-middleware TS conflict error

### ISSUE THREAD

**Issue by IlCallo** [freddy38510/quasar-app-extension-ssg#24]
Seems like there is a TS conflict generated by different version of `http-proxy-middleware`.
See https://github.com/DefinitelyTyped/DefinitelyTyped/issues/45479

```
ERROR in /home/---/node_modules/@types/webpack-dev-server/index.d.ts(30,53):
TS2694: Namespace '"/home/---/node_modules/http-proxy-middleware/dist/index"' has no exported member 'Config'.
ERROR in /home/---/node_modules/@types/webpack-dev-server/index.d.ts(36,29):
TS2694: Namespace '"/home/---/node_modules/http-proxy-middleware/dist/index"' has no exported member 'Config'.
Version: typescript 3.9.5, eslint 6.8.0
```

```
yarn why v1.22.5
[1/4] Why do we have the module "http-proxy-middleware"...?
[2/4] Initialising dependency graph...
[3/4] Finding dependency...
[4/4] Calculating file sizes...
=> Found "http-proxy-middleware@1.0.5"
info Reasons this module exists
   - "quasar-app-extension-ssg" depends on it
   - Hoisted from "quasar-app-extension-ssg#http-proxy-middleware"
info Disk size without dependencies: "380KB"
info Disk size with unique dependencies: "6.57MB"
info Disk size with transitive dependencies: "11.79MB"
info Number of shared dependencies: 30
=> Found "webpack-dev-server#http-proxy-middleware@0.19.1"
info This module exists because "@quasar#app#webpack-dev-server" depends on it.
info Disk size without dependencies: "80KB"
info Disk size with unique dependencies: "5.42MB"
info Disk size with transitive dependencies: "9.92MB"
info Number of shared dependencies: 28
```

Don't really know how and if this can be solved on your part, but at least now you know :)

**Comment by freddy38510** [comment]
@IlCallo From my understanding, there is one dependency of `http-proxy-middleware@0.19.x` in `@quasar/app` coming from the dependency `webpack-dev-server` itself.

There is another dependency of `http-proxy-middleware@1.x.x` in `@quasar/cli` package used by its own `serve` command.

The `serve` command of this app extension involves `@quasar/app` package, i think the conflict is coming from here.

**Comment by IlCallo** [comment]
Exactly, and `webpack-dev-server` will have updated dep with version 4 (not yet out).
When `webpack-dev-server` v4 is out and @quasar/app updates it, you can revert back to how you were doing previously. That's why I said to mark it in some way, so you can check again in some months if the problem is solved upstream

**Comment by freddy38510** [comment]
I pinned this issue, waiting for [`webpack-dev-server` v4](https://github.com/webpack/webpack-dev-server/pull/2592) out and updated in `@quasar/app`.

Thanks @IlCallo !

**Comment by vahost** [comment]
> It works! 

What works? What's the fix?

**Comment by freddy38510** [comment]
> What works? What's the fix?

@vahost The fix is to avoid using differents versions of `http-proxy-middleware` in your project, resulting in a types conflict.

In this App Extension i was using version `http-proxy-middleware@1.x.x` while the dependency `webpack-dev-server` is using the version `http-proxy-middleware@0.19.x`.

**Comment by gDev95** [comment]
Still don't understand how you fixed this. I have the same problem after `@quasar/app` to v2.2.1 and can also confirm that i have two different versions of `http-proxy-middleware` 

```
info Reasons this module exists
   - "@quasar#app#webpack-dev-server" depends on it
   - Hoisted from "@quasar#app#webpack-dev-server#http-proxy-middleware"
info Disk size without dependencies: "312KB"
info Disk size with unique dependencies: "5.72MB"
info Disk size with transitive dependencies: "9.74MB"
info Number of shared dependencies: 35
=> Found "@types/http-proxy-middleware#http-proxy-middleware@1.0.6"
info This module exists because "@quasar#app#@types#webpack-dev-server#@types#http-proxy-middleware" depends on it.
info Disk size without dependencies: "128KB"
info Disk size with unique dependencies: "6.41MB"
info Disk size with transitive dependencies: "11.14MB"
info Number of shared dependencies: 37
``` 

Still i cannot read out steps or a general solution to remove on dependency here
