### ISSUE TITLE
Compatibility with @quasar/app 2.1.0

### ISSUE THREAD

**Issue by IlCallo** [freddy38510/quasar-app-extension-ssg#25]
Seems like something breaks when using the AE with `@quasar/app` v2.1.0

![image](https://user-images.githubusercontent.com/10036108/93087054-503f2980-f698-11ea-8acc-64e2dbf36851.png)

I see you already tried to address this in https://github.com/freddy38510/quasar-app-extension-ssg/commit/afd9e2549dde6fb44dcf964a534183db97067294 but seems like something isn't working anyway.

Glancing over the code, the fix you proposed seems right, I'm gonna try to dig deeper when I find some time and stick to `@quasar/app` v2.0.8 until then

**Comment by freddy38510** [comment]
@IlCallo thanks for reporting this issue.

I will look further into it later this week, i have higher priorities, the days are too short :)

For your information, i made a lot of progress regarding the FOUC issue. I will come back to you with more details.

**Comment by IlCallo** [comment]
Thank you for working on this!
Can't wait to see the progress you made ;)

**Comment by freddy38510** [comment]
@IlCallo I made a mistake by switching webpackConf and quasarConf :s

**Comment by IlCallo** [comment]
Well, it's a good thing the bug was a simple variable misplacement :laughing:
