### ISSUE TITLE
Could not find module "browsers-support" while building

### ISSUE THREAD

**Issue by saifobeidat** [freddy38510/quasar-app-extension-ssg#26]
I am trying to generate Static Pages using this extension by this command : `build:ssg': 'quasar ssg generate` but it fails with following error `   Error: Cannot find module 'C:\Users\user\repos\abwaabv2\node_modules\@quasar\app\lib\helpers\browsers-support'`

Here's a screenshot of the issue:
![image](https://user-images.githubusercontent.com/24841143/95212753-b2ea9780-07f6-11eb-8847-5bdb28530df7.png)

`(node:18516) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:18516) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
`

I am not sure, how can I get this "browsers-supports"?

Any insights please.

**Comment by freddy38510** [comment]
@saifobeidat thanks for reporting this issue.

Which version of `@quasar/app` are you using ?

You can see the file `browsers-support.js' added in this commit https://github.com/quasarframework/quasar/commit/cd2c38aec6e7347368c3fcee7ca44faf5b53d0cf

**Comment by saifobeidat** [comment]
Thanks @freddy38510  for your quick answer, the version is `"@quasar/app": "^1.8.10"`..

should I upgrade to make it work?

**Comment by freddy38510** [comment]
This file was added in `@quasar/app@2.0.0`, sorry for this drawback. You don't have to update Quasar if you don't want/need to.
Please update this extension and tell me if the issue is fixed for you, thanks :)

**Comment by saifobeidat** [comment]
@freddy38510 Thanks, the error has gone.. but I face another issue, I will be posting it separately.
