### ISSUE TITLE
Does not support Vite

### ISSUE THREAD

**Issue by SKFrozenCloud** [freddy38510/quasar-app-extension-ssg#263]
Getting this error when adding SSG to a Quasar project that uses Vite:

`App • ⚠️  Extension(ssg): Dependency not found - @quasar/app. Please install it.`

EDIT: I think standard webpack is `@quasar/app` while Vite is `@quasar/app-vite`

**Comment by freddy38510** [comment]
Hi,

The extension does not currently support Vite. I plan to implement it very soon, but I can't say how long it will take.

Please, keep watching this issue if you want to follow the progress.

**Comment by freddy38510** [comment]
Actually, the standard webpack package is `@quasar/app-webpack` since the version 3.4.0.

I fixed this in [this commit](https://github.com/freddy38510/quasar-app-extension-ssg/commit/e6669d5273529ac2afcc143273f6e9d75038fc17).

**Comment by freddy38510** [comment]
@SKFrozenCloud,

I would be glad if you could try the [new version](https://www.npmjs.com/package/quasar-app-extension-ssg/v/4.4.0) supporting Vite.js.

Please, let me know if everything works fine.
