### ISSUE TITLE
Need a demo 

### ISSUE THREAD

**Issue by kostyfisik** [freddy38510/quasar-app-extension-ssg#269]
may be you can create (and support to the latest release of your plug-in) a public demo, it is really pleasant to see a perfect Google Lighthouse score using a very basic free hosting.... [link]( https://pagespeed.web.dev/report?url=https%3A%2F%2F62d814fcbc3d2700768fba0e--glistening-chaja-3455df.netlify.app%2F&form_factor=desktop
)
[My try](https://62d814fcbc3d2700768fba0e--glistening-chaja-3455df.netlify.app/)
[Git]( https://github.com/kostyfisik/quasar-ssg-demo)

![Screenshot from 2022-07-20 17-48-31](https://user-images.githubusercontent.com/5239997/180013369-43cb40a9-7526-4a80-ac84-6839af8c28d2.png)
![Screenshot from 2022-07-20 17-48-35](https://user-images.githubusercontent.com/5239997/180013383-f99929ef-e4d6-45b9-9297-bfa19825c889.png)

**Comment by freddy38510** [comment]
Hello,

I really like the idea and appreciate your contribution.

In the documentation, I mainly focused on the technique without ever really highlighting the performance or the interest of using this extension.

Actually, I'm working on vite.js support. I've made good progress and it should be done soon. After that, I'll add a demo with `lighthouse` results to the documentation.

Thanks @kostyfisik !

**Comment by freddy38510** [comment]
I'm glad you found this extension useful.

About Vite.js support, the `quasar ssg generate` command is successfully implemented (locally on my computer, no pushed commits yet).

SSG + PWA is already supported, and it will for Quasar app using Vite.js too. You just need to enable it by setting `ssr.pwa` to `true` in your Quasar config file.

The tricky part now is the `quasar ssg dev` command with Vite.js support.

SSG is simple for production. The extension pre-render the HTML code for each page and write it to the corresponding "index.html" file. But when it comes to local development with hot reloading, it becomes "weird" to write html to a file when a page is requested by the browser.

Actually Quasar SSR mode with the dev command might do the trick, but I want the developer experience to be as close to the production version as possible without sacrificing too much speed for local development.

The `quasar ssg dev` command should handle all SSG edge cases before the developer runs into any issues after the production version is deployed.

**Comment by freddy38510** [comment]
@kostyfisik ,

I just released a [new version](https://www.npmjs.com/package/quasar-app-extension-ssg/v/4.4.0) supporting Vite.js, if you want to try it and give me some feedbacks that would be awesome.

**Comment by kostyfisik** [comment]
@freddy38510 LG2M, thank you! I'll check if we can use it in production... it looks pretty promising to improve our web-service...
