### ISSUE TITLE
There're no generated routes in the dist/ssg directory

### ISSUE THREAD

**Issue by saifobeidat** [freddy38510/quasar-app-extension-ssg#27]
I am trying to generate some routes, so I added the following in the quasar.conf.js 

`ssg: {
			routes: ['/ar', '/ar/explore/10', '/ar/explore/11']
		},`

and used this command to  generate the above routes: `npm run build:ssg`

The build was completed but with an error:  ` Extension(ssg) · ⚠️    TypeError: d.Cookies.has is not a function`

![image](https://user-images.githubusercontent.com/24841143/95672661-78dd1500-0bab-11eb-818d-4ea01e0cb964.png)

Note: I am using `Cookies` helper from Quasar.

And I checked the dist/ssg folder, and found that the plugin has generated the needed static files (CSS, JS, Images), but it didn't generate the HTML pages  

![image](https://user-images.githubusercontent.com/24841143/95672715-ceb1bd00-0bab-11eb-8fcd-3f0825cedf70.png)

Data might be helpful:

`"quasar": "^1.11.3"`
`"@quasar/app": "^1.8.10"`
`"@quasar/extras": "^1.8.1"`

**Comment by freddy38510** [comment]
@saifobeidat,
How do you import and use the Cookies plugin ? There is a [note ](https://quasar.dev/quasar-plugins/cookies#Notes-on-SSR) about how to do it for SSR in Quasar documentation.

Also you should keep in mind that no headers from the client are sent to the server when your pages are prerendered/generated. So, it means that there is no Cookies available from the client at server side.

**Comment by saifobeidat** [comment]
@freddy38510 I am importing the Cookies plugin like this `import { Cookies } from 'quasar'` .. and yes it's mentioned that it should be changed to another form when using SSR mode.. but I am not using this mode,, Thanks.

**Comment by freddy38510** [comment]
@saifobeidat 
This app extension is using SSR mode to prerender pages, so actually you are using it.

Let me clarify the difference between SSR mode and SSG mode:
- In SSR mode, routes are rendered on a server then served to a client.
- In SSG mode, routes are rendered on a server the same way as in SSR mode, but **at build time**, then saved to static html files.

If you need more explanations, do not hesistate to ask me.

**Comment by saifobeidat** [comment]
@freddy38510 Thanks,

I have made some temporarily changes such as removing the usage of Coockie, and yes the errors have gone but and new errors related the `window `came out.. it seems those plugins/object are being called at the server side and cause errors as we don't have for example `window `object at the server-side.. so my question is how to avoid those objects from being called at the server-side? should I check the `process.env.` each time before I use a client side object/plugin ? or there's a global way to handle this?

sorry I am very new at these things.

**Comment by freddy38510** [comment]
You should write your code with SSR mode in mind. There is a good starting point in Quasar documentation about [how to write universal code](https://quasar.dev/quasar-cli/developing-ssr/writing-universal-code). 

You might take a look at the [components lifecycle hooks](https://quasar.dev/quasar-cli/developing-ssr/writing-universal-code#Component-Lifecycle-Hooks) first.
Then, if you are using some boot files, you can let them run only on server or client like [explained in the documentation](https://quasar.dev/quasar-cli/developing-ssr/writing-universal-code#Boot-Files).

At last resort, yes you can use `process.env.SERVER` and `process.env.CLIENT`.

Could you see from where the `window` object is called ?
