### ISSUE TITLE
Wrong check for mobile when fixing body classes

### ISSUE THREAD

**Issue by pdanpdan** [freddy38510/quasar-app-extension-ssg#279]
Here

https://github.com/freddy38510/quasar-app-extension-ssg/blob/cb42a42535ea8f0be368855e84cf99695e53fc1c/src/boot/ssg-corrections.js#L26

the check is done against `void 0` but the function returns `'ios'`, `'android'` or `''`.

You can return `'platform-ios'`, `'platform-android'` or `''` from function and skip the check, of check against `''`

**Comment by freddy38510** [comment]
Hello,

Thanks for checking out the code, I appreciate that!

Quasar performs the exact same check in the [`body.js` file](https://github.com/quasarframework/quasar/blob/dev/ui/src/body.js#L19). Also, looking at the function [`getMobilePlatform`](https://github.com/quasarframework/quasar/blob/dev/ui/src/body.js#L6,) I think it returns `'ios'`, `'android'` or `undefined`.

So in case the value is `undefined` I'm not sure it's a good idea to concatenate `undefined` with a string.

**Comment by pdanpdan** [comment]
Of course is not a good idea - but now all non-mobile will receive a `platform-` class (function returns empty string instead of `void 0`

**Comment by freddy38510** [comment]
You were absolutely right, I misread the code thinking that the `getMobilePlatform` function came from the Platform Quasar plugin.

My bad, I was initially returning an empty string to fix linting errors :s

Thanks for opening this issue !
