### ISSUE TITLE
Does not refresh modified dependencies

### ISSUE THREAD

**Issue by vandelpavel** [freddy38510/quasar-app-extension-ssg#28]
I'm using [this Quasar AppExtension](https://github.com/dreamonkey/quasar-app-extension-meta) to manage tags and meta.
I'm currently working on that AE so i added a local dependency to test my progress. I noticed that while in dev or ssr mode every time i modify the AE and i run `yarn add -D ../path` and `quasar ext invoke @dreamonkey/meta` everithing works just fine. With this AE i always need instead to delete my dist folder, uninvoke and delete that dependency, re add and re invoke it and finally run `quasar ssg generate`.
I also tried to delete my node modules and update them but nothing changes.
Any clues if i'm doing something wrong?

**Comment by freddy38510** [comment]
If i refer to the [Quasar documentation](https://quasar.dev/app-extensions/development-guide/introduction#Install-and-prompts-scripts), to develop localy an app extension, you should add it to the dependencies like this:

```bash
$ yarn add --dev file://path/to/our/app/ext/root
# or
$ yarn add --dev link://path/to/our/app/ext/root
```
If you don't want to repeat the uninstall and install procedures, just follow the [Developing](https://github.com/freddy38510/quasar-app-extension-ssg#developing) section of the readme.

The only difference i can think of between this AE and this [one](https://github.com/dreamonkey/quasar-app-extension-meta), is that `quasar-app-extension-ssg` package is not published yet.

PS: On which platform are you working ? Linux, MacOS or Windows ?

**Comment by freddy38510** [comment]
@vandelpavel,

I published the AE to NPM. Could you try to update it, and tell me if you still have this issue please ?

**Comment by vandelpavel** [comment]
Same project, same AE but all migrated to V2.
Still need to do that 'hack' in order to refresh the other AE dependecy.

To be clear i launch ``yarn add ../path`` then '`quasar ext invoke <name>`` and the build still use the older dependency.
If i delete node modules and re install them it works.

(Sorry if late)
