### ISSUE TITLE
Client only / SSG Dummy Data

### ISSUE THREAD

**Issue by adzbuck** [freddy38510/quasar-app-extension-ssg#283]
I have an AJAX api request that's run on a page is loaded, however I don't want it to trigger when being built. I'd like it to substitute the request for some predefined data. Is this possible?

I tried using a condition: process.env.MODE === 'ssg' however that changed the generated code so it also didn't run the AJAX.

I also had a look at the proxy, but I can't work out how to prevent the request and set the response to predefined data.

**Comment by freddy38510** [comment]
The initial data must be the same between the server and the client in order to avoid [hydration mismatch](https://vuejs.org/guide/scaling-up/ssr.html#hydration-mismatch).

If you want to change these data after hydration at client-side, you can use the `onMounted` Vue hook which will be executed only at-client side.

**Comment by freddy38510** [comment]
I will try to provide you a simple example based on your needs @adzbuck

**Comment by adzbuck** [comment]
It's not so much changing the data, it's more I don't want to give my build server access to the API.
So I'd want api.xxx.com/example to be replaced with ./build-data/example.js

It would be a great feature if you could display something for SSG then it gets swapped out after hydration.
e.g. a sidebar with the users profile, for SSG It would display a skeleton loader/loader of some sort.. once it's hydrated it hit's the API and swaps it for the real content.

Is this possible at all?

**Comment by freddy38510** [comment]
In the example I provided the API is never accessed at server-side.

You can replace the initial data by a loading template then with `v-if="data === null"` and `v-else` you can switch to the "real content" as soon as the data are fetched at client-side from the onMounted hook.

**Comment by adzbuck** [comment]
Ah ok, thenk you.. I didn't realise onMounted didn't run on SSG. I can work with that. Thank you for your support.
