### ISSUE TITLE
undefined ls-remote -h -t

### ISSUE THREAD

**Issue by shaxper** [freddy38510/quasar-app-extension-ssg#29]
I try to install this extension and get the next:

D:\Projects\quasor\qsanche>quasar ext add ssg
 App · Installing "ssg" Quasar App Extension

 App · Retrieving "quasar-app-extension-ssg"...
 App · [sync] Running "npm install --save-dev quasar-app-extension-ssg"

npm ERR! code ENOENT
npm ERR! syscall spawn git
npm ERR! path git
npm ERR! errno ENOENT
npm ERR! enoent Error while executing:
npm ERR! enoent undefined ls-remote -h -t https://github.com/freddy38510/critters.git
npm ERR! enoent
npm ERR! enoent
npm ERR! enoent spawn git ENOENT
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

 App · ⚠️  Command "npm" failed with exit code: 1
 App · ⚠️  Failed to install quasar-app-extension-ssg

**Comment by freddy38510** [comment]
@shaxper It seems that you need to install `Git` on your system.

I guess that you are on Windows, you can follow this [guide](https://github.com/git-guides/install-git#install-git-on-windows).
