### ISSUE TITLE
Automatic patch of ES Module import

### ISSUE THREAD

**Issue by nicolashefti** [freddy38510/quasar-app-extension-ssg#309]
Hi,

I'm using the extension with a Quasar 2 project. I get the following error:

```
Error [ERR_REQUIRE_ESM]: require() of ES Module /**/ not supported.
Instead change the require of swiper-vue.js in /**/ server-entry.js to a dynamic import() which is available in all CommonJS modules
  /**/
  code: 'ERR_REQUIRE_ESM'
}
```

The error message very clear and I am able to patch manually the server-entry.js file, using `import` instead of `require`.

Manual patch is ok but it has two limitations:
- Everytime a project file changes, I need to re-patch the file
- In a CI/CD pipeline this is not pratical to patch the server-entry.js file

Is there a way to fix this import once for all?

**Comment by freddy38510** [comment]
Related to #85.

Swiper is an ES module only, you need to transpile it to work at server-side.

```js
// quasar.conf.js
module.exports = configure((ctx) => ({
  build: {
    transpileDependencies: ['swiper', 'swiper/vue', 'ssr-window', 'dom7'],
  }
});
```
