### ISSUE TITLE
InjectManifest doesn't build the custom-service-worker

### ISSUE THREAD

**Issue by lukadriel7** [freddy38510/quasar-app-extension-ssg#32]
Hello again,
Using InjectManifest causes the custom-service-worker file to be copied as is in the distribution folder without building it.
It causes error on run-time when using imports in the custom-service-worker.js file since webpack isn't used to create the file.

I don't know if the behaviour was intended so I thought it might be better to open an issue about that.

Best regards

**Comment by freddy38510** [comment]
@lukadriel7,

Thanks again for finding this issue. You're right, InjectManifest method does not compile service worker with [`workbox-build` ](https://developers.google.com/web/tools/workbox/modules/workbox-build)as it does with [`workbox-webpack-plugin`](https://developers.google.com/web/tools/workbox/modules/workbox-webpack-plugin).

It should now compile it with webpack, using Quasar webpack config, in the last published version [`1.0.3`](https://www.npmjs.com/package/quasar-app-extension-ssg/v/1.0.3).

Again, you can upgrade the app extension:
```bash
quasar ext add ssg
```

Then build your app with the argument `force-build` if you didn't change your sources files:
```bash
quasar ssg generate --force-build
```

Please, tell me if it's working good for you now.
