### ISSUE TITLE
I get the error message "Cannot find module 'ouch''" when running "quasar ssg dev" on freshly scaffolded quasar project

### ISSUE THREAD

**Issue by gregorred** [freddy38510/quasar-app-extension-ssg#357]
Hello,

The error occurs on a freshly scaffolded quasar project, I didn't change anything in the project (except installing the ssg extension).

Steps to reproduce:

1. Scaffold a new quasar project via **npm init quasar**
✔ What would you like to build? › App with Quasar CLI, let's go!
✔ Project folder: … default
✔ Pick Quasar version: › Quasar v2 (Vue 3 | latest and greatest)
✔ Pick script type: › Typescript
✔ Pick Quasar App CLI variant: › Quasar App CLI with Vite
✔ Package name: … default
✔ Project product name: (must start with letter if building mobile apps) … default
✔ Project description: … default
✔ Author: … Gregor
✔ Pick a Vue component style: › Composition API with <script setup>
✔ Pick your CSS preprocessor: › Sass with SCSS syntax
✔ Check the features needed for your project: › ESLint, State Management (Pinia), Axios, Vue-i18n
✔ Pick an ESLint preset: › Prettier

2. Install ssg extension via **quasar ext add ssg**
? Add scripts into your package.json ? Yes
? Add auto-completion of ssg property of quasar.config.js file for IDE ? Yes
? Inline critical css and async load the rest ? Yes

3. Run **quasar ssg dev** , output and error below
 App • Looking for Quasar App Extension "ssg" command "dev"
 App • Running "ssg" Quasar App Extension...
 App • Running "ssg" > "dev" command

node:internal/modules/cjs/loader:985
  const err = new Error(message);
              ^

Error: Cannot find module 'ouch'
Require stack:
- /home/home/projects/test/node_modules/quasar-app-extension-ssg/src/vite/app-paths.js
- /home/home/projects/test/node_modules/quasar-app-extension-ssg/src/vite/helpers/packages.js
- /home/home/projects/test/node_modules/quasar-app-extension-ssg/src/vite/helpers/logger.js
- /home/home/projects/test/node_modules/quasar-app-extension-ssg/src/vite/cmd/dev.js
- /home/home/projects/test/node_modules/quasar-app-extension-ssg/src/index.js
- /home/home/projects/test/node_modules/@quasar/app-vite/lib/app-extension/Extension.js
- /home/home/projects/test/node_modules/@quasar/app-vite/lib/cmd/run.js
- /home/home/projects/test/node_modules/@quasar/app-vite/bin/quasar
- /home/home/.nvm/versions/node/v16.18.1/lib/node_modules/@quasar/cli/bin/quasar.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:985:15)
    at Function.resolve (node:internal/modules/cjs/helpers:109:19)
    at Object.appNodeModule (/home/home/projects/test/node_modules/quasar-app-extension-ssg/src/vite/app-paths.js:43:38)
    at module.exports.requireFromApp (/home/home/projects/test/node_modules/quasar-app-extension-ssg/src/vite/helpers/packages.js:24:61)
    at Object.<anonymous> (/home/home/projects/test/node_modules/quasar-app-extension-ssg/src/vite/ssg-devserver.js:24:14)
    at Module._compile (node:internal/modules/cjs/loader:1155:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1209:10)
    at Module.load (node:internal/modules/cjs/loader:1033:32)
    at Function.Module._load (node:internal/modules/cjs/loader:868:12)
    at Module.require (node:internal/modules/cjs/loader:1057:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/home/projects/test/node_modules/quasar-app-extension-ssg/src/vite/app-paths.js',
    '/home/home/projects/test/node_modules/quasar-app-extension-ssg/src/vite/helpers/packages.js',
    '/home/home/projects/test/node_modules/quasar-app-extension-ssg/src/vite/helpers/logger.js',
    '/home/home/projects/test/node_modules/quasar-app-extension-ssg/src/vite/cmd/dev.js',
    '/home/home/projects/test/node_modules/quasar-app-extension-ssg/src/index.js',
    '/home/home/projects/test/node_modules/@quasar/app-vite/lib/app-extension/Extension.js',
    '/home/home/projects/test/node_modules/@quasar/app-vite/lib/cmd/run.js',
    '/home/home/projects/test/node_modules/@quasar/app-vite/bin/quasar',
    '/home/home/.nvm/versions/node/v16.18.1/lib/node_modules/@quasar/cli/bin/quasar.js'
  ]
}

The other commands **quasar ssg generate** & **quasar ssg serve** work

**Comment by freddy38510** [comment]
Hello,

I've just published a [new version](https://www.npmjs.com/package/quasar-app-extension-ssg/v/5.0.0) that contains a fix for the issue in question.

I hadn't done so yet, as further breaking changes are planned.

Don't hesitate to open a new issue if you have any problems.

**Comment by gregorred** [comment]
Hi,

thanks for releasing a bit earlier then. Really appreciate that you fix issues always so fast. Sent you some coffee money as a little thank you

**Comment by freddy38510** [comment]
Hi,

This is much appreciated. I am truly grateful for your support !
