### ISSUE TITLE
minifyOptions error?

### ISSUE THREAD

**Issue by altezza04** [freddy38510/quasar-app-extension-ssg#366]
After update Quasar to V2.12.7, anyone experience the error? 

TypeError: Cannot read properties of undefined (reading 'minifyOptions')

**Comment by freddy38510** [comment]
@altezza04,

I've published a [new version](https://www.npmjs.com/package/quasar-app-extension-ssg/v/5.0.2) with the corrections. Let me know if you have any problems.
