### ISSUE TITLE
Create custom SSG commands

### ISSUE THREAD

**Issue by IlCallo** [freddy38510/quasar-app-extension-ssg#4]
Instead of piggybacking on SSR build step, we should create some standalone commands.
Currently it's not possible to enhance existing commands AFAIK (so no `quasar [dev/build] -ssg`), but we can go with something which look similar and change it later if it becomes possible.

I was thinking about `quasar dev-ssg`  and `quasar build-ssg`

**Comment by JeffSpies** [comment]
I think this is a good plan until we can add build modes.

**Comment by freddy38510** [comment]
Added in https://github.com/freddy38510/quasar-app-extension-ssg/commit/0cbd59791801013d1544f381a97d70be22da283f
