### ISSUE TITLE
Output build into `/build/ssg`

### ISSUE THREAD

**Issue by IlCallo** [freddy38510/quasar-app-extension-ssg#5]
For the same reason behind #3, the output should be put into an ad-hoc folder for SSG.
It could be an idea to also allow specifying the output folder, but I don't actually have an use case in mind for this, once the build folder is already separated from other modes.

**Comment by freddy38510** [comment]
Fixed in https://github.com/freddy38510/quasar-app-extension-ssg/commit/2bab4ff83e29cbdbc61a4c1b73e8208725a10557.
See here https://github.com/freddy38510/quasar-app-extension-ssg#builddir for details.
