### ISSUE TITLE
[Question] Is it possible to build SPA with only specified routes as static webpages?

### ISSUE THREAD

**Issue by yeus** [freddy38510/quasar-app-extension-ssg#86]
is it possible to tell the plugin to only generate static code for one specific route or component?

I have a product webpage which updates its product-data only on rare occasions and I would like to generate a static side by pulling the product information from a database and then pre-rendering it duing build stage. but I would only like to render the specific product webpages (only 3) into static code. Is this possible?

Thx for the great addon otherwise! I hope it gets included into quasar main build at some point...

**Comment by freddy38510** [comment]
@lostnet,

I didn't found a better way than compiling the router with webpack https://github.com/freddy38510/quasar-app-extension-ssg/commit/d0d94e12079cf1753ca61b2d666edbc2852563a7. The trick here is to replace any imported Vue component by a [fake component](https://github.com/freddy38510/quasar-app-extension-ssg/blob/master/src/webpack/fake-vue-component.js) to avoid having a big compiled file including all Vue components.

And of course, the webpack configuration used is derived from the server-side one. So we have all process.env and aliases needed.

**Comment by lostnet** [comment]
@freddy38510 I tried it out on my test project and it works well! On my real project I am actually setting the paths in the data of the vue components, i.e. `[Component].data().path` so it notices very quickly that it is fake. I think my method is not the normal way to do it, but I could not find any examples that were DRY where every page needed to know their own route.

**Comment by freddy38510** [comment]
I'm a little bit confused. Don't you set your app routes from [the `src/router/routes.js` file](https://quasar.dev/quasar-cli/routing) ?

Why your pages need to know their own route ?

**Comment by lostnet** [comment]
@freddy38510  I'd originally encapsulated everything to go along with the data for the Meta plugin within a page back on saber (which had no explicit router config?)  I think I had some concerns with how large the router config itself was when I migrated to the early quasar-ssg, but it looks like I am now passing Meta's data in the confusingly similar `$route.meta` in to get it to the parent/Layout component. So I think it currently would just reduce the size if I moved all the data to the `routes.js` in my current setup.

There's not really any technical reason the path needed to go with Meta's data, but my odds are pretty high of breaking something if I'm not looking at canonical links and paths at the same time..
