### ISSUE TITLE
Rename extension name to `quasar-app-extension-ssg`

### ISSUE THREAD

**Issue by IlCallo** [freddy38510/quasar-app-extension-ssg#9]
Same reason behind #7, `static` is a very generic word too.
`quasar ext add static` is a bit generic, `quasar ext add ssg` is already clearer

The AE name is expecially important because once a package is added to NPM I think it's impossible to remove it, you can just deprecate it, and littering the registry with duplicates would cause confusion in the ecosystem

**Comment by freddy38510** [comment]
Fixed in https://github.com/freddy38510/quasar-app-extension-ssg/commit/f6f9bea6303d87d12b0f792fb1fc05ba8a92d9a1
